name: Build Windows EXE

on:
  push:
    branches:
      - main   # 触发条件：推送到 main 分支
  workflow_dispatch:   # 支持手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build exe with PyInstaller
        run: |
          pyinstaller --onefile server.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: app-exe
          path: dist/server.exe

